#!/bin/bash
echo "$1"

# create selection string
selection_string="terminal_browser gui_browser downloader youtube-dl"
quality_selection_string="240 360 480 720 description plain"

# choose action
select choice in $selection_string 
do
    case $choice in
        "terminal_browser")
			$BROWSER "$1"
            ;;

        "gui_browser")
			$GUI_BROWSER "$1"
            ;;

        "downloader")
            $DOWNLOADER "$1"
            ;;

        #"media_viewer")
		#	$MEDIA_VIEWER "$1"
        #    ;;

        "youtube-dl")
            select quality in $quality_selection_string
            do
                case $quality in
                    "plain")
                        youtube-dl "$1"
                        ;;
                    "240")
                        youtube-dl --add-metadata -ic -f "bestvideo[height<=240]+bestaudio/best[height<=240]" "$1"
                        ;;
                    "360")
                        youtube-dl --add-metadata -ic -f "bestvideo[height<=360]+bestaudio/best[height<=360]" "$1"
                        ;;
                    "480")
                        youtube-dl --add-metadata -ic -f "bestvideo[height<=480]+bestaudio/best[height<=480]" "$1"
                        ;;
                    "720")
                        youtube-dl --add-metadata -ic -f "bestvideo[height<=720]+bestaudio/best[height<=720]" "$1"
                        ;;
                    "description")
                        youtube-dl --get-description --skip-download "$1" | less
                        ;;
                esac

                exit
            done
            ;;
    esac

    exit
done

